# Pandas basics topics
* Input data
* Overview of data
* Selecting data on a DataFrame
* Combining DataFrames
* Handling missing values
* Reshaping a DataFrame
* Other pandas functions


##### Importing the Pandas library

In [1]:
import pandas as pd
import numpy as np

1. We read data from a file and convert to a DataFrame.
2. Pandas provide functions to read data from many different file types. 
3. The most commonly used is read_csv.

In [2]:
df=pd.read_csv('/Users/manishkumar/Downloads/nba.csv')

In [3]:
df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [4]:
df.columns


Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [5]:
df.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [6]:
df['Salary'][10]

2569260.0

In [7]:
df.tail()

Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler   
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN   
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN   
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas   
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN   

        Salary  
453  2433333.0  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [9]:
df.shape

(458, 9)

In [10]:
df.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [11]:
df.mean()

Number    1.767834e+01
Age       2.693873e+01
Weight    2.215230e+02
Salary    4.842684e+06
dtype: float64

In [12]:
arun = pd.DataFrame({'Name':['Arun','Raghavendra','Sai','Pavan'],'Rollno':[1,2,3,4]})

In [13]:
arun

Name  Rollno
0         Arun       1
1  Raghavendra       2
2          Sai       3
3        Pavan       4

In [14]:
arun.drop('Rollno',axis=1)

Name
0         Arun
1  Raghavendra
2          Sai
3        Pavan

In [15]:
sachin = pd.DataFrame({'Name':'Sachin','Age':23,'Qualification':'B.tech','Department':'CSE','Domain':'Data Science'},index=[1])

In [16]:
sachin

Name  Age Qualification Department        Domain
1  Sachin   23        B.tech        CSE  Data Science

In [17]:
arun

Name  Rollno
0         Arun       1
1  Raghavendra       2
2          Sai       3
3        Pavan       4

# Day-2

Two type data structure in pandas
* Series
* DataFrame

In [18]:
dict2 = {100:['Sachin','arun'],'sachin':[100,200]}
df1 = pd.DataFrame(dict2,index=[0,1])

In [19]:
df1

100  sachin
0  Sachin     100
1    arun     200

In [20]:
df1[100] # Series

0    Sachin
1      arun
Name: 100, dtype: object

In [21]:
d = df1.to_csv('students.csv')

In [22]:
pd.read_csv('students.csv')

Unnamed: 0     100  sachin
0           0  Sachin     100
1           1    arun     200

In [23]:
seri = pd.Series(np.random.rand(30))

In [24]:
seri

0     0.687419
1     0.856136
2     0.222782
3     0.581216
4     0.311306
5     0.312561
6     0.246305
7     0.728067
8     0.664129
9     0.182294
10    0.402209
11    0.186625
12    0.649618
13    0.065344
14    0.630528
15    0.283331
16    0.606618
17    0.425039
18    0.290605
19    0.405890
20    0.890085
21    0.664375
22    0.875770
23    0.229723
24    0.926421
25    0.923934
26    0.597515
27    0.928868
28    0.202092
29    0.079756
dtype: float64

# Day - 3

## Sorting of dataframe
* Sort object by labels (along an axis).

In [25]:
country = [['Afghanistan', 1952, 8425333, 'Asia'],
            ['Australia', 1957, 9712569, 'Oceania'],
            ['Brazil', 1962, 76039390, 'Americas'],
            ['China', 1957, 637408000, 'Asia'],
            ['France', 1957, 44310863, 'Europe'],
            ['India', 1952, 3.72e+08, 'Asia'],
            ['United States', 1957, 171984000, 'Americas']]
  

In [26]:
df3 = pd.DataFrame(country)

In [27]:
df3

0     1            2         3
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

df4 = pd.DataFrame(data, index, columns)

In [28]:
df4 = pd.DataFrame(country,columns=['Country','Year','Population','Continent'])

In [29]:
df4

Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [30]:
df4.sort_index(axis=0)

Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [31]:
df4.sort_index()

Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [32]:
df4.sort_index(axis=1)

Continent        Country   Population  Year
0      Asia    Afghanistan    8425333.0  1952
1   Oceania      Australia    9712569.0  1957
2  Americas         Brazil   76039390.0  1962
3      Asia          China  637408000.0  1957
4    Europe         France   44310863.0  1957
5      Asia          India  372000000.0  1952
6  Americas  United States  171984000.0  1957

In [33]:
df4.sort_values(by = 'Continent')

Country  Year   Population Continent
2         Brazil  1962   76039390.0  Americas
6  United States  1957  171984000.0  Americas
0    Afghanistan  1952    8425333.0      Asia
3          China  1957  637408000.0      Asia
5          India  1952  372000000.0      Asia
4         France  1957   44310863.0    Europe
1      Australia  1957    9712569.0   Oceania

In [34]:
df4.sort_values(by = ['Population','Country'])

Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
4         France  1957   44310863.0    Europe
2         Brazil  1962   76039390.0  Americas
6  United States  1957  171984000.0  Americas
5          India  1952  372000000.0      Asia
3          China  1957  637408000.0      Asia

# Selecting data 

loc vs iloc

In [35]:
# loc
df4.loc[6]

Country       United States
Year                   1957
Population      171984000.0
Continent          Americas
Name: 6, dtype: object

In [36]:
df4

Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [37]:
# To acess single column 
df4['Country']

0      Afghanistan
1        Australia
2           Brazil
3            China
4           France
5            India
6    United States
Name: Country, dtype: object

In [38]:
df4.Country     # we can access single column with . operator as well 
               # but if we have the column name which includes space than square brackets are used.

0      Afghanistan
1        Australia
2           Brazil
3            China
4           France
5            India
6    United States
Name: Country, dtype: object

In [39]:
# to access multiple column

df4[    ['Country','Population','Year']      ]

Country   Population  Year
0    Afghanistan    8425333.0  1952
1      Australia    9712569.0  1957
2         Brazil   76039390.0  1962
3          China  637408000.0  1957
4         France   44310863.0  1957
5          India  372000000.0  1952
6  United States  171984000.0  1957

In [40]:
li = ['Country','Population','Year'] 
df4[li]

Country   Population  Year
0    Afghanistan    8425333.0  1952
1      Australia    9712569.0  1957
2         Brazil   76039390.0  1962
3          China  637408000.0  1957
4         France   44310863.0  1957
5          India  372000000.0  1952
6  United States  171984000.0  1957

In [41]:
# to access an entity or element
df4['Country'][1]

'Australia'

In [42]:
# to change values
df4['Population'][2]

76039390.0

In [43]:
df4['Population'][2] = 61003200

<ipython-input-43-149845271f04>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Population'][2] = 61003200


In [44]:
# Add a column in existing dataframe
growth = [10,11,14,7,8,15,12]
df4['Growth (%)'] = growth

In [45]:
df4

Country  Year   Population Continent  Growth (%)
0    Afghanistan  1952    8425333.0      Asia          10
1      Australia  1957    9712569.0   Oceania          11
2         Brazil  1962   61003200.0  Americas          14
3          China  1957  637408000.0      Asia           7
4         France  1957   44310863.0    Europe           8
5          India  1952  372000000.0      Asia          15
6  United States  1957  171984000.0  Americas          12

In [46]:
# Slicing and indexing
df4[2:6]

# only rows whose index is 2 to index 5 will be printed. Index 6 is not included here.

Country  Year   Population Continent  Growth (%)
2  Brazil  1962   61003200.0  Americas          14
3   China  1957  637408000.0      Asia           7
4  France  1957   44310863.0    Europe           8
5   India  1952  372000000.0      Asia          15

In [47]:
# and to print everything both are used
df4[:]  # = df4

Country  Year   Population Continent  Growth (%)
0    Afghanistan  1952    8425333.0      Asia          10
1      Australia  1957    9712569.0   Oceania          11
2         Brazil  1962   61003200.0  Americas          14
3          China  1957  637408000.0      Asia           7
4         France  1957   44310863.0    Europe           8
5          India  1952  372000000.0      Asia          15
6  United States  1957  171984000.0  Americas          12

In [48]:
# max() of data

df4['Population'].max()  # maximum value of column

637408000.0

So the maximum value from population column is 637408000.0

In [49]:
df4.max()   #. maximum value from all the columns

Country       United States
Year                   1962
Population      637408000.0
Continent           Oceania
Growth (%)               15
dtype: object

In [50]:
# min() of data
df4['Population'].min()

8425333.0

In [51]:
df4.min()  # minimum value from all the columns

Country       Afghanistan
Year                 1952
Population      8425333.0
Continent        Americas
Growth (%)              7
dtype: object

* Afghanistan is minimum value from country column because it starts with A
* 1952 is the min value from Year column
* 8425333.0 is the minimum from Population column
* Americas is the minimum because it also starts with A
* 7% is the lowest growth in Growy=th column

## Accessing the filtered dataframe

In [52]:
df4

Country  Year   Population Continent  Growth (%)
0    Afghanistan  1952    8425333.0      Asia          10
1      Australia  1957    9712569.0   Oceania          11
2         Brazil  1962   61003200.0  Americas          14
3          China  1957  637408000.0      Asia           7
4         France  1957   44310863.0    Europe           8
5          India  1952  372000000.0      Asia          15
6  United States  1957  171984000.0  Americas          12

In [53]:
# I want only those entries whose population is more than 9712579.

df4[df4.Population>=9712579]

Country  Year   Population Continent  Growth (%)
2         Brazil  1962   61003200.0  Americas          14
3          China  1957  637408000.0      Asia           7
4         France  1957   44310863.0    Europe           8
5          India  1952  372000000.0      Asia          15
6  United States  1957  171984000.0  Americas          12

In [54]:
# Now I only want the max population with conditional select

df4[df4.Population==df4['Population'].max()]

Country  Year   Population Continent  Growth (%)
3   China  1957  637408000.0      Asia           7

In [55]:
# Now I want the country name whose population is maximum

df4['Country'][df4.Population==df4['Population'].max()]

3    China
Name: Country, dtype: object

China has the maximum population.

In [56]:
# Now I want the country name and continent whose population is maximum

df4[['Country','Continent']][df4.Population==df4['Population'].max()]

Country Continent
3   China      Asia

In [57]:
# change column names

#df4.rename(columns = {'Population':'Janshankya'})

# If i chganged inplace = True than it will reflect in my original dataframe

In [58]:
df4

Country  Year   Population Continent  Growth (%)
0    Afghanistan  1952    8425333.0      Asia          10
1      Australia  1957    9712569.0   Oceania          11
2         Brazil  1962   61003200.0  Americas          14
3          China  1957  637408000.0      Asia           7
4         France  1957   44310863.0    Europe           8
5          India  1952  372000000.0      Asia          15
6  United States  1957  171984000.0  Americas          12

### Set any column as index

In [59]:
df4.set_index('Year',inplace = True)
# This change is not a permanent change

In [60]:
df4

Country   Population Continent  Growth (%)
Year                                                  
1952    Afghanistan    8425333.0      Asia          10
1957      Australia    9712569.0   Oceania          11
1962         Brazil   61003200.0  Americas          14
1957          China  637408000.0      Asia           7
1957         France   44310863.0    Europe           8
1952          India  372000000.0      Asia          15
1957  United States  171984000.0  Americas          12

In [61]:
df4.reset_index(inplace = True)

In [62]:
df4

Year        Country   Population Continent  Growth (%)
0  1952    Afghanistan    8425333.0      Asia          10
1  1957      Australia    9712569.0   Oceania          11
2  1962         Brazil   61003200.0  Americas          14
3  1957          China  637408000.0      Asia           7
4  1957         France   44310863.0    Europe           8
5  1952          India  372000000.0      Asia          15
6  1957  United States  171984000.0  Americas          12